CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTE(
	
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

CREATE TABLE LIVROS(
LIVRO VARCHAR (30),
AUTOR VARCHAR (30),
SEXO  CHAR    (1),
PAGINAS VARCHAR   (1000),
VALOR   FLOAT  (8),
ESTADO  CHAR   (2),
ANO INT (4),
EDITORA VARCHAR (30)
);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, VALOR, ESTADO, ANO, EDITORA) VALUES ('Cavaleiro Real', 'Ana Claudia'	'F', '465', 49.9, 'RJ', 2009, 'Atlas');

SELECT *FROM LIVROS;
SELECT LIVRO, EDITORA FROM LIVROS;
SELECT LIVRO, ESTADO FROM LIVROS WHERE SEXO = 'M';
SELECT LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';
SELECT LIVRO, VALOR FROM LIVROS WHERE ESTADO = 'SP';

SELECT LIVRO, ESTADO FROM LIVROS WHERE SEXO = 'M' AND ESTADO = 'SP' AND 'RJ';
SELECT LIVRO, ESTADO FROM LIVROS WHERE SEXO = 'M' AND (ESTADO = 'SP' OR ESTADO = 'RJ');

