INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

SELECT NOME, SEXO, RUA, BAIRRO /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
    INER JOIN ENDERECO /*JUNÇÃO */
    ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, RUA, BAIRRO /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
    INER JOIN ENDERECO /*JUNÇÃO */
    ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */